title: Партитури хор
author: Христо Николов

execute:
  execute_notebooks: off

latex:
  latex_documents:
    targetname: book.tex


bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/executablebooks/jupyter-book  
  path_to_book: docs  
  branch: main

html:
  use_issues_button: false
  use_repository_button: true
  css_files:
    - css/styles.css